application: gae-python-rest
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /_api/simpleUser.*
  script: simpleUser.app

- url: /_api/simple.*
  script: simple.app
  

#- url: .*
#  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
